# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy locally a DAOS virtual cluster

version: "3.8"

services:

  daos_base:
    image: "daos-base:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-base/el8"
      args:
        - "RHEL_BASE_IMAGE_NAME=${RHEL_BASE_IMAGE_NAME}"
        - "RHEL_BASE_IMAGE_TAG=${RHEL_BASE_IMAGE_TAG}"
        - "BUST_CACHE=${BUST_CACHE}"
        - "DAOS_AUTH=${DAOS_AUTH}"
        - "DAOS_REPOS=${DAOS_REPOS}"
        - "DAOS_GPG_KEYS=${DAOS_GPG_KEYS}"
        - "DAOS_REPOS_NOAUTH=${DAOS_REPOS_NOAUTH}"
    # FIXME Refine needed capabilities
    privileged: true
    volumes:
      - type: bind
        read_only: true
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /run

  daos_server:
    image: "daos-server:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-server/el8"
      args:
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
        - "DAOS_AUTH=${DAOS_AUTH}"
        - "DAOS_HUGEPAGES_NBR=${DAOS_HUGEPAGES_NBR}"
        - "DAOS_IFACE_NAME=${DAOS_IFACE_NAME}"
        - "DAOS_SCM_SIZE=${DAOS_SCM_SIZE}"
        - "DAOS_BDEV_SIZE=${DAOS_BDEV_SIZE}"
        - "DAOS_MD_ON_SSD=${DAOS_MD_ON_SSD}"
    container_name: daos-server
    hostname: daos-server
    # FIXME Refine needed capabilities
    privileged: true
    # FIXME virtual network such as bridge are not yet supported
    network_mode: host
    # FIXME List of hosts needed until virtual network will be supported
    extra_hosts:
      - "daos-server:${DAOS_IFACE_IP}"
      - "daos-admin:${DAOS_IFACE_IP}"
      - "daos-client:${DAOS_IFACE_IP}"
    volumes:
      - type: bind
        read_only: true
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: bind
        read_only: false
        source: /dev/hugepages
        target: /dev/hugepages
      - type: bind
        read_only: false
        source: /sys/kernel/mm/hugepages
        target: /sys/kernel/mm/hugepages
      - type: bind
        read_only: false
        source: /sys/devices/system/node
        target: /sys/devices/system/node
      - type: tmpfs
        target: /run

  daos_admin:
    image: "daos-admin:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-admin/el8"
      args:
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
        - "DAOS_AUTH=${DAOS_AUTH}"
    container_name: daos-admin
    hostname: daos-admin
    # FIXME Refine needed capabilities
    privileged: true
    # FIXME virtual network such as bridge are not yet supported
    network_mode: host
    # FIXME List of hosts needed until virtual network will be supported
    extra_hosts:
      - "daos-server:${DAOS_IFACE_IP}"
      - "daos-admin:${DAOS_IFACE_IP}"
      - "daos-client:${DAOS_IFACE_IP}"
    volumes:
      - type: bind
        read_only: true
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /run
    depends_on:
      - daos_server

  daos_client:
    image: "daos-client:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-client/el8"
      args:
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
        - "DAOS_AUTH=${DAOS_AUTH}"
        - "DAOS_AGENT_IFACE_CFG=${DAOS_AGENT_IFACE_CFG}"
        - "DAOS_AGENT_IFACE_NUMA_NODE=${DAOS_AGENT_IFACE_NUMA_NODE}"
        - "DAOS_AGENT_IFACE_NAME=${DAOS_AGENT_IFACE_NAME}"
        - "DAOS_AGENT_IFACE_DOMAIN_NAME=${DAOS_AGENT_IFACE_DOMAIN_NAME}"
    container_name: daos-client
    hostname: daos-client
    # FIXME Refine needed capabilities
    privileged: true
    # FIXME virtual network such as bridge are not yet supported
    network_mode: host
    # FIXME List of hosts needed until virtual network will be supported
    extra_hosts:
      - "daos-server:${DAOS_IFACE_IP}"
      - "daos-admin:${DAOS_IFACE_IP}"
      - "daos-client:${DAOS_IFACE_IP}"
    volumes:
      - type: bind
        read_only: true
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /run
    depends_on:
      - daos_server
